# Generated by Django 3.1.1 on 2020-09-29 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        ('estabelecimento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='estabelecimento.estabelecimento')),
                ('produtos', models.ManyToManyField(blank=True, null=True, to='produtos.Produto')),
            ],
        ),
    ]
