# Generated by Django 3.1.1 on 2020-09-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='dono_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
