# Generated by Django 3.1.1 on 2020-09-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('estabelecimento', '0002_estabelecimento_dono_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='produtos',
            field=models.ManyToManyField(blank=True, null=True, to='produtos.Produto'),
        ),
    ]
